openapi: 3.0.0
info:
  title: "sample swagger"
  description: "aaaaaaa"
  version: 1.0.0
paths:
  /users/{userId}:
    $ref: "./paths/users.userId.yml"
  /users:
    $ref: "./paths/users.yml"
components:
  schemas:
    $ref: "./schemas/index.yml"